sudo: required
services:
  - docker
before_install:
  - docker build -t wanwanzainaer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wanwanzainaer/react-test npm run test
#
after_success:
  - docker build -t wanwanzainaer/multi-client ./client
  - docker build -t wanwanzainaer/multi-nginx ./nginx
  - docker build -t wanwanzainaer/multi-server ./server
  - docker build -t wanwanzainaer/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wanwanzainaer/multi-client
  - docker push wanwanzainaer/multi-nginx
  - docker push wanwanzainaer/multi-server
  - docker push wanwanzainaer/multi-worker
